version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/vk-miniapp"

  - package-ecosystem: "npm"
    directory: "/boilerplate"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/vk-miniapp"
