name: 'Checks'

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Lint code
        run: |
          yarn
          yarn lint
  check_script:
    runs-on: ${{ matrix.os }}
    if: ${{ success() && contains(github.base_ref, 'master') }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x, 14.x, 16.x, latest]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Create Mini App with NodeJS ${{ matrix.node }} on ${{ matrix.os }}
        run: npm run create ./mini-app -- --template typescript
