on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - name: Publushing release
        run: yarn lint
