name: 'Checks'

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install Node.js dependencies
        run: rm yarn.lock && yarn install
      - name: Lint Prettier
        run: yarn lint:prettier
      - name: Lint ESLint
        run: yarn lint:eslint
  check_script:
    runs-on: ${{ matrix.os }}
    if: ${{ success() && contains(github.base_ref, 'master') }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x, latest]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Create Mini App with NodeJS ${{ matrix.node }} on ${{ matrix.os }}
        run: npx https://github.com/VKCOM/create-vk-mini-app#${{ github.head_ref }} mini-app --typescript --template=vkapp-ui
