name: 'Publish (pre-release)'

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'version type (use prerelease for bumping pre-release version):'
        required: true
        type: choice
        default: 'prerelease'
        options:
          - pre-patch
          - pre-minor
          - pre-major
          - pre-release
      npm_tag:
        required: true
        description: 'NPM tag:'
        type: choice
        default: 'beta'
        options:
          - alpha
          - beta
          - rc
      custom_version:
        description: 'use syntax x.y.z-beta.0, without "v" (it ignore "version type" parameter):'
        required: false

run-name: Publish pre-release create-vk-mini-app ${{ inputs.new_version }} ${{ inputs.custom_version }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setting up the repository environment
        uses: ./.github/actions/setup

      - name: Bump version
        uses: ./.github/actions/bump-version
        with:
          version: ${{ github.event.inputs.custom_version || github.event.inputs.new_version }}
          npm_tag: ${{ github.event.inputs.npm_tag }}

      - name: Complete publish
        uses: ./.github/actions/complete-publish
        with:
          branch: ${{ github.ref }}
          prev_version: ${{ steps.updated_versions_info.outputs.prev_version }}
          next_version: ${{ steps.updated_versions_info.outputs.next_version }}
          npm_tag: ${{ github.event.inputs.npm_tag }}
