name: 'Publish (pre-release)'

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'tag ("beta" or "alpha"):'
        type: choice
        default: 'beta'
        options:
          - beta
          - alpha
      version:
        description: 'version: x.y.z-beta.0 or x.y.z-alpha.0 (without "v")'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - run: yarn version --new-version "${{ github.event.inputs.version }}" --no-commit-hooks

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publishing release
        run: yarn publish --access public --non-interactive --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
